package de.th.wildau.recruiter.ejb;

public enum BusinessError {

	ACCOUNT_COULD_NOT_ACTIVATE, ACCOUNT_NOT_ACTIVE, INVALID_VIEW_ID, SIGNIN_FAILED, SIGNIN_RESET_ACTIVATION_KEY, THIS_IS_NOT_YOURS, USER_ALREADY_EXIST;

}
